Repository GoogleCloudPlatform/guest-configs, pull requests merged in 2021-08, with the labels that each got.

#26 dont set IP in etc/hosts; remove rsyslog
  packaging/debian/control
  packaging/debian/install
  packaging/google-compute-engine.spec
  src/etc/rsyslog.d/90-google.conf
  src/usr/bin/google_set_hostname
Labels: cla: yes, lgtm, approved, size/M

#25 Fix NVMe partition names
  src/lib/udev/rules.d/65-gce-disk-naming.rules
Labels: size/XS, cla: yes, lgtm, needs-ok-to-test, approved

#27 restore rsyslog
  packaging/debian/control
  packaging/debian/install
  packaging/google-compute-engine.spec
  src/etc/rsyslog.d/90-google.conf
Labels: cla: yes, size/S, lgtm, approved
