Repository GoogleCloudPlatform/guest-configs, pull requests merged in 2024-09, with the labels that each got.

#65 Update packaging as of Ubuntu devel packaging
  packaging/ubuntu/91-gce.cfg
  packaging/ubuntu/99-gce.rules
  packaging/ubuntu/NEWS
  packaging/ubuntu/changelog
  packaging/ubuntu/compat
  packaging/ubuntu/control
  packaging/ubuntu/copyright
  packaging/ubuntu/gbp.conf
  packaging/ubuntu/install
  packaging/ubuntu/instance_configs.cfg.distro
  packaging/ubuntu/links
  packaging/ubuntu/lintian-overrides
  packaging/ubuntu/preinst
  packaging/ubuntu/rules
  packaging/ubuntu/source/format
  packaging/ubuntu/source/lintian-overrides
  packaging/ubuntu/watch
Labels: lgtm, approved, ok-to-test, size/XL

#77 Include systemd-networkd hook in Ubuntu packaging
  packaging/ubuntu/install
Labels: size/XS, lgtm, approved

#75 Call google_set_hostname on openSUSE and when the agent is configured to manage hostname and FQDN, let it.
  src/etc/sysconfig/network/scripts/google_up.sh
  src/usr/bin/google_set_hostname
Labels: lgtm, approved, size/M
