Repository GoogleCloudPlatform/guest-configs, pull requests merged in 2024-10, with the labels that each got.

#78 Always use IP from primary NIC in the networkd-dispatcher routable hook
  packaging/debian/control
  packaging/ubuntu/control
  src/etc/sysconfig/network/scripts/google_up.sh
  src/usr/lib/networkd-dispatcher/routable.d/google_hostname.sh
Labels: size/S, lgtm, approved

#80 Depend on jq in enterprise linux
  packaging/google-compute-engine.spec
Labels: size/XS, lgtm, approved

#81 Update OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#79 Update google_set_multiqueue to enable on A3Ultra family
  src/usr/bin/google_set_multiqueue
Labels: size/XS, lgtm, approved, ok-to-test

#82 Add GCE-specific config for systemd-resolved
  packaging/debian/install
  packaging/google-compute-engine.spec
  packaging/ubuntu/install
  src/etc/systemd/resolved.conf.d/gce-resolved.conf
Labels: size/S, lgtm, approved

#83 Update google_set_multiqueue to skip set_irq if nic is not a gvnic device
  src/usr/bin/google_set_multiqueue
Labels: lgtm, approved, ok-to-test, size/M

#84 Add GCE intent based NIC naming tools
  src/lib/udev/rules.d/75-gce-network.rules
  src/usr/bin/gce-nic-naming
Labels: lgtm, approved, ok-to-test, size/XL
