Repository GoogleCloudPlatform/guest-configs, pull requests merged in 2024-11, with the labels that each got.

#85 Remove Apt IPv4 only config for Debian and Ubuntu.
  src/etc/apt/apt.conf.d/99ipv4-only
Labels: size/XS, lgtm, approved

#86 gce-nic-naming: exit 1 so that udev ignores the rule on error
  src/usr/bin/gce-nic-naming
Labels: size/S, lgtm, approved

#87 Revert 3 commits
  src/lib/udev/rules.d/75-gce-network.rules
  src/usr/bin/gce-nic-naming
  src/usr/bin/google_set_multiqueue
Labels: lgtm, approved, size/XL

#89 Restore NIC naming tools and google_set_multiqueue changes
  src/lib/udev/rules.d/75-gce-network.rules
  src/usr/bin/gce-nic-naming
  src/usr/bin/google_set_multiqueue
Labels: lgtm, approved, size/XL

#91 Remove IDPF devices from renaming rules
  src/lib/udev/rules.d/75-gce-network.rules
  src/usr/bin/gce-nic-naming
Labels: size/XS, lgtm, needs-ok-to-test, approved

#92 Temporarily revert google_set_multiqueue changes for release
  src/usr/bin/google_set_multiqueue
Labels: lgtm, approved, size/M
