Repository GoogleCloudPlatform/guest-configs, pull requests merged in 2024-12, with the labels that each got.

#94 Depend on networkd-dispatcher in Ubuntu
  packaging/ubuntu/control
Labels: size/XS, lgtm, approved

#93 Restore google_set_multiqueue changes for A3Ultra
  src/usr/bin/google_set_multiqueue
Labels: lgtm, approved, size/M

#90 Update google_set_multiqueue to configure vCPU ranges based on VM platform
  src/usr/bin/google_set_multiqueue
Labels: lgtm, approved, ok-to-test, size/M

#97 Remove Pat from owners file.
  OWNERS
Labels: size/XS, lgtm, approved
