Repository GoogleCloudPlatform/guest-configs, pull requests merged in 2025-01, with the labels that each got.

#95 Restore IDPF devices for renaming rules
  src/lib/udev/rules.d/75-gce-network.rules
  src/usr/bin/gce-nic-naming
Labels: lgtm, approved, ok-to-test, size/M

#98 Add GPL-2 to licensing information
  LICENSE
  packaging/debian/copyright
Labels: lgtm, approved, size/L

#88 Also force virtio_scsi.
  src/etc/dracut.conf.d/gce.conf
Labels: size/XS, lgtm, do-not-merge/hold, approved
